<?php
/**
 * Created by PhpStorm.
 * User: AmauryD
 * Date: 02-05-18
 * Time: 10:38
 */

namespace Framework\Model\Entity;


use Framework\Model\Entity;

class Categorie extends Entity
{
    /**
     * @param EntityProperty $property
     * @return mixed
     */
    protected function onPropertySet(EntityProperty &$property)
    {

    }

    /**
     * @param EntityProperty $property
     * @return mixed
     */
    protected function onPropertyGet(EntityProperty &$property)
    {
        if (is_string($property->value()))
            return htmlspecialchars($property->value());
        return parent::onPropertyGet($property); // TODO: Change the autogenerated stub
    }
}