<?php
/**
 * Created by PhpStorm.
 * User: AmauryD
 * Date: 18-04-18
 * Time: 11:11
 */

namespace Framework\Model\Entity;


use Framework\Model\Entity;

class Forum extends Entity
{
    /**
     * @param EntityProperty $property
     * @return mixed
     */
    protected function onPropertySet(EntityProperty &$property)
    {
        // TODO: Implement onPropertySet() method.
    }

    protected function onPropertyGet(EntityProperty &$property)
    {
        if (is_string($property->value()))
            return htmlspecialchars($property->value());
        return parent::onPropertyGet($property); // TODO: Change the autogenerated stub
    }
}