<?php
/**
 * Created by PhpStorm.
 * User: AmauryD
 * Date: 18-04-18
 * Time: 11:11
 */

namespace Framework\Model\Entity;


use Framework\Model\Entity;

class User extends Entity
{

    /**
     * @param EntityProperty $property
     * @return mixed
     */
    protected function onPropertySet(EntityProperty &$property)
    {
        if (!$this->isNew())
            return;

        switch ($property->getName()) {
            case "password":
                $property->set(
                    password_hash($property->value(), PASSWORD_DEFAULT)
                );
                break;
        }

        return;
    }

    protected function onPropertyGet(EntityProperty &$property)
    {
        if (is_string($property->value()))
            return htmlspecialchars($property->value());
        return parent::onPropertyGet($property); // TODO: Change the autogenerated stub
    }
}