<?php
/**
 * Created by PhpStorm.
 * User: AmauryD
 * Date: 19-05-18
 * Time: 10:54
 */

namespace template\Controller;


use Framework\Controller\Controller;

class BaseController extends Controller
{

    public function index()
    {
        // TODO: Implement index() method.
    }

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected function beforeAction()
    {
        parent::beforeAction();
    }

    protected function isAuthorized()
    {
        if (strtolower($this->request->getParameter('prefix')) === 'admin') {
            if (isset($_SESSION['user'])) return $_SESSION['user']->get('role') === 'admin';
            return false;
        }
        return parent::isAuthorized(); // TODO: Change the autogenerated stub
    }
}