<?php
/**
 * Created by PhpStorm.
 * User: AmauryD
 * Date: 13-05-18
 * Time: 15:42
 */

namespace framework\Exception;


use Throwable;

class Exception extends \Exception
{
    protected $title;

    public function __construct($message = "", $title = '', $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
        if ($title != "")
            $this->title = $title;
    }

    public function title()
    {
        return $this->title;
    }

    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }

    public function __wakeup()
    {
        parent::__wakeup(); // TODO: Change the autogenerated stub
    }
}